export interface BusOperator {
    operatorId?: number; // Optional if using for POST requests (auto-generated by backend)
    name: string;
    email: string;
    password: string;
    phoneNumber: string;
  }